(()=>{'use strict';
const URL='https://viqufxlcxwgboyxbdhjb.supabase.co';
const KEY='sb_publishable_zdfvnwwgL9LI3yTK0-1Sbg_RsYRvNge';
const LOGO='/flix2watch-logo-red-v34.png';
const db=window.f2wSupabase||window.sb||window.supabase.createClient(URL,KEY);
const PAGE_SIZE=25, REFRESH_MS=30000, CACHE_TTL=120000;
let page=1,busy=false,view='xp',filter='',lastRefresh=0,nextRefreshAt=Date.now()+REFRESH_MS,myUserId='',rowsNow=[],totalNow=0;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Intl.NumberFormat().format(Number(n||0));
const time=m=>{m=Math.max(0,Number(m||0));if(m<60)return `${fmt(m)}m`;const h=Math.floor(m/60),mm=Math.floor(m%60);return h<1000?`${fmt(h)}h ${mm}m`:`${fmt(h)}h`};
const profile=u=>{location.href='/profile/?user='+encodeURIComponent(u)};
const metricMap={xp:['XP','score',v=>`${fmt(v)} XP`],titles:['Titles watched','titles_watched',fmt],watch:['Watch time','watch_minutes',time],ratings:['Ratings','ratings_count',fmt],achievements:['Achievements','achievements',fmt]};
function cacheKey(){return `f2w_lb_v140_p${page}`}
function saveCache(rows,total,stats){try{localStorage.setItem(cacheKey(),JSON.stringify({ts:Date.now(),rows,total,stats}))}catch{}}
function readCache(){try{const v=JSON.parse(localStorage.getItem(cacheKey())||'null');return v&&Date.now()-Number(v.ts||0)<CACHE_TTL?v:null}catch{return null}}
function role(r){return r?`<span class="role">${esc(r)}</span>`:''}
function pod(r,place){if(!r)return '';return `<article class="podium-card ${place===1?'first':''}" data-user="${esc(r.username)}"><div class="pod-rank">#${place}</div>${place===1?'<div class="crown"><i class="fa-solid fa-crown"></i></div>':''}<div class="avatar-wrap"><img class="avatar" src="${esc(r.avatar_url||LOGO)}" onerror="this.src='${LOGO}'"><i class="presence ${r.online?'on':''}"></i></div><h3>${esc(r.display_name||r.username)}</h3><div class="handle">@${esc(r.username)}</div>${role(r.top_role)}<div class="score">${fmt(r.score)} XP</div></article>`}
function row(r){const isMe=myUserId&&r.user_id===myUserId;return `<article class="rank-row ${Number(r.rank_no)<=10?'is-top10':''} ${isMe?'is-me':''}" data-search="${esc((r.display_name||'')+' '+(r.username||''))}"><div class="rank-no">#${fmt(r.rank_no)}</div><div class="user" data-user="${esc(r.username)}"><img src="${esc(r.avatar_url||LOGO)}" onerror="this.src='${LOGO}'"><div class="user-copy"><strong>${esc(r.display_name||r.username)} ${r.online?'<i class="fa-solid fa-circle" style="font-size:7px;color:#28e78d"></i>':''}${isMe?'<span class="lb140-rank-change"><i class="fa-solid fa-user"></i> YOU</span>':''}</strong><small>@${esc(r.username)} ${r.top_role?'· '+esc(r.top_role):''}</small></div></div><div class="metric" data-metric="titles"><b>${fmt(r.titles_watched)}</b><span>Titles</span></div><div class="metric hide-md" data-metric="watch"><b>${time(r.watch_minutes)}</b><span>Watch time</span></div><div class="metric hide-md" data-metric="ratings"><b>${fmt(r.ratings_count)}</b><span>Ratings</span></div><div class="metric" data-metric="achievements"><b>${fmt(r.achievements)}</b><span>Badges</span></div><div class="row-score" data-metric="xp">${fmt(r.score)} XP</div><div class="chev"><i class="fa-solid fa-chevron-right"></i></div></article>`}
function bindProfiles(){document.querySelectorAll('[data-user]').forEach(x=>x.onclick=()=>profile(x.dataset.user))}
function setView(next){if(!metricMap[next])next='xp';view=next;document.querySelectorAll('.lb140-tab').forEach(b=>{const on=b.dataset.view===view;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});document.querySelectorAll('.metric').forEach(m=>m.classList.toggle('is-focus',m.dataset.metric===view));const score=document.querySelectorAll('.row-score');score.forEach(s=>s.style.outline=view==='xp'?'1px solid color-mix(in srgb,var(--lb140-accent) 24%,transparent)':'none');const label=metricMap[view][0];const note=$('#lb140-view-note');if(note)note.innerHTML=`Viewing <b>${esc(label)}</b>. <span class="xp-lock"><i class="fa-solid fa-lock"></i> Rank order always stays XP-based.</span>`;try{history.replaceState(null,'',view==='xp'?location.pathname:`${location.pathname}?view=${encodeURIComponent(view)}`)}catch{}}
function applyFilter(){const q=filter.trim().toLowerCase();document.querySelectorAll('.rank-row').forEach(el=>{el.style.display=!q||String(el.dataset.search||'').toLowerCase().includes(q)?'':'none'});const shown=[...document.querySelectorAll('.rank-row')].filter(x=>x.style.display!=='none').length;const empty=$('#lb140-filter-empty');if(empty)empty.hidden=!q||shown>0}
function render(rows,total){rowsNow=rows;totalNow=total;const list=$('#list'),podium=$('#podium');if(list)list.innerHTML=rows.map(row).join('')||'<div class="empty">No ranked profiles yet.</div>';if(page===1&&podium){const top=rows.slice(0,3);podium.innerHTML=pod(top[1],2)+pod(top[0],1)+pod(top[2],3)}else if(podium)podium.innerHTML='';pager(total);bindProfiles();setView(view);applyFilter()}
function renderStats(r){if(!r)return;$('#count')&&($('#count').textContent=fmt(r.registered_players));$('#online')&&($('#online').textContent=fmt(r.online_now));$('#watch')&&($('#watch').textContent=time(r.combined_watch_minutes));}
function pager(total){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));const st=$('#pageStat');if(st)st.textContent=`${page} / ${pages}`;const host=$('#pager');if(!host)return;let h=`<button class="pagebtn" data-p="${page-1}" ${page===1?'disabled':''} aria-label="Previous page"><i class="fa-solid fa-chevron-left"></i></button>`;for(let p=Math.max(1,page-2);p<=Math.min(pages,page+2);p++)h+=`<button class="pagebtn ${p===page?'active':''}" data-p="${p}">${p}</button>`;h+=`<button class="pagebtn" data-p="${page+1}" ${page===pages?'disabled':''} aria-label="Next page"><i class="fa-solid fa-chevron-right"></i></button>`;host.innerHTML=h;host.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{const p=Number(b.dataset.p);if(p<1||p>pages||p===page)return;page=p;const c=readCache();if(c){render(c.rows||[],Number(c.total||0));renderStats(c.stats)}refreshAll(true);window.scrollTo({top:Math.max(0,document.querySelector('.lb140-toolbar')?.offsetTop-100||0),behavior:'smooth'})})}
async function refreshAll(manual=false){if(busy)return;busy=true;const btn=$('#lb140-refresh-btn');if(btn)btn.disabled=true;const updated=$('#updated');if(updated)updated.textContent=manual?'Refreshing now…':'Updating rankings…';try{const [lb,st]=await Promise.all([db.rpc('get_public_leaderboard',{p_page:page,p_page_size:PAGE_SIZE,p_sort:'overall'}),db.rpc('get_public_leaderboard_stats')]);if(lb.error)throw lb.error;if(st.error)throw st.error;const rows=Array.isArray(lb.data)?lb.data:[],total=Number(rows[0]?.total_count||0),stats=Array.isArray(st.data)?st.data[0]:st.data;render(rows,total);renderStats(stats);saveCache(rows,total,stats);lastRefresh=Date.now();nextRefreshAt=lastRefresh+REFRESH_MS;if(updated)updated.textContent='Updated '+new Date(lastRefresh).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});}catch(e){console.error('Leaderboard v140 refresh failed:',e);if(!rowsNow.length&&$('#list'))$('#list').innerHTML=`<div class="empty error"><b>Could not load rankings.</b><br><br>${esc(e?.message||'Unknown leaderboard error.')}</div>`;if(updated)updated.textContent='Update failed · keeping last good data';}finally{busy=false;if(btn)btn.disabled=false}}
function tick(){const left=Math.max(0,Math.ceil((nextRefreshAt-Date.now())/1000));const el=$('#lb140-countdown');if(el)el.textContent=busy?'Updating…':`Next update ${left}s`;if(left<=0&&!busy)refreshAll(false)}
function bind(){document.querySelectorAll('.lb140-tab').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#lb140-refresh-btn')?.addEventListener('click',()=>refreshAll(true));$('#lb140-filter')?.addEventListener('input',e=>{filter=e.target.value||'';applyFilter()});}
async function initAuth(){try{const {data}=await db.auth.getUser();myUserId=data?.user?.id||'';const logged=!!myUserId;for(const id of ['favorites-nav-btn','profile-nav-btn','support-nav-btn','account-btn']){const el=document.getElementById(id);if(el)el.style.display=logged?'':'none'}const li=$('#header-login-btn'),su=$('#header-signup-btn');if(li)li.style.display=logged?'none':'';if(su)su.style.display=logged?'none':'';if(logged){const {data:p}=await db.from('profiles').select('username').eq('user_id',myUserId).maybeSingle();window.f2wLbMyUsername=p?.username||'';render(rowsNow,totalNow)}}catch{}}
window.openHeaderAuth=()=>location.href='/home/';window.openAccountModal=()=>location.href='/home/';window.openMyProfile=()=>{const u=window.f2wLbMyUsername||'';if(u)location.href='/profile/?user='+encodeURIComponent(u);else location.href='/home/'};
let presenceSession='';async function heartbeat(){try{const {data:{session}}=await db.auth.getSession();if(!session?.user||document.visibilityState==='hidden')return;if(!presenceSession){presenceSession=sessionStorage.getItem('f2w_presence_session_v17')||crypto.randomUUID();sessionStorage.setItem('f2w_presence_session_v17',presenceSession)}const {error}=await db.rpc('touch_presence_v17',{p_session_id:presenceSession});if(error)await db.rpc('touch_presence')}catch{}}
try{const raw=new URL(location.href).searchParams.get('view');if(metricMap[raw])view=raw}catch{}
const cached=readCache();if(cached){render(cached.rows||[],Number(cached.total||0));renderStats(cached.stats);const u=$('#updated');if(u)u.textContent='Showing cached rankings · checking for updates…'}
bind();initAuth();heartbeat();refreshAll(false);setInterval(tick,1000);setInterval(heartbeat,30000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){heartbeat();if(Date.now()-lastRefresh>=REFRESH_MS)refreshAll(false)}});
document.getElementById('user-search')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&typeof window.submitUserDirectorySearch==='function')window.submitUserDirectorySearch()});
})();
