-- Flix2Watch v166 — stable site-wide notifications + mark-all-read
create table if not exists public.f2w_notifications_v125(
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  title text not null default 'Notification',
  message text not null default '',
  link text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);
create index if not exists f2w_notifications_v166_user_idx on public.f2w_notifications_v125(user_id,created_at desc);
alter table public.f2w_notifications_v125 enable row level security;

drop function if exists public.get_my_notifications_v166(integer);
create function public.get_my_notifications_v166(p_limit integer default 60)
returns table(id bigint,title text,message text,link text,created_at timestamptz,read_at timestamptz)
language sql security definer set search_path=public as $$
  select n.id,n.title,n.message,n.link,n.created_at,n.read_at
  from public.f2w_notifications_v125 n
  where n.user_id=auth.uid()
  order by n.created_at desc
  limit greatest(1,least(coalesce(p_limit,60),100));
$$;
revoke all on function public.get_my_notifications_v166(integer) from public;
grant execute on function public.get_my_notifications_v166(integer) to authenticated;

drop function if exists public.mark_my_notifications_read_v166();
create function public.mark_my_notifications_read_v166()
returns integer language plpgsql security definer set search_path=public as $$
declare n integer;
begin
  update public.f2w_notifications_v125
  set read_at=coalesce(read_at,now())
  where user_id=auth.uid() and read_at is null;
  get diagnostics n=row_count;
  return n;
end$$;
revoke all on function public.mark_my_notifications_read_v166() from public;
grant execute on function public.mark_my_notifications_read_v166() to authenticated;

do $$ begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='f2w_notifications_v125'
  ) then
    alter publication supabase_realtime add table public.f2w_notifications_v125;
  end if;
end $$;
